#!/bin/sh

set -xe

# Install via `gem install git-up`
git up
# Build with prod env
npm run build-prod
# Check out build branch
git checkout build-production
# Copy from build dir to root
cp -r dist/* .
# Add all files
git add --all
# Commit build files
git commit -m "Update build - `date -u`"
# Push to remote
if [ $1 = "production" ]; then
  git push 5apps build-production:master
else
  git push 5apps_staging build-production:master
fi
git push origin build-production:build-production
# Go back to master branch
git checkout master
